# Generated by Django 4.1.4 on 2023-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='imgpath',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productimg',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='productid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
