# Generated by Django 4.1.4 on 2023-01-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_users_user_rename_imgpath_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=70),
        ),
    ]
