# Generated by Django 4.1.4 on 2023-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdes',
            field=models.CharField(max_length=500),
        ),
    ]
