# Generated by Django 4.1.3 on 2023-02-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_alter_product_productdes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('contactno', models.BigIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=70)),
                ('productprice', models.IntegerField()),
                ('productdes', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='photos')),
                ('qty', models.IntegerField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategoryid',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userid',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='orderdetails',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
